export const ADD_ARTIFACT = "ADD_ARTIFACT";
export const RM_ARTIFACT = "RM_ARTIFACT";
export const EDIT_ARTIFACT = "EDIT_ARTIFACT";
export const ARTIFACT_SWITCH = "ARTIFACT_SWITCH";
export const FILTER_ARTIFACTS = "FILTER_ARTIFACTS";
export const LAUNCH_SNACKBAR = "LAUNCH_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";