export const ADD_ARTIFACT = "ADD_ARTIFACT";
export const RM_ARTIFACT = "RM_ARTIFACT";
export const EDIT_ARTIFACT = "EDIT_ARTIFACT";
export const ARTIFACT_SWITCH = "ARTIFACT_SWITCH";

export const LAUNCH_DELETE_SNACKBAR = "LAUNCH_DELETE_SNACKBAR";
export const LAUNCH_EDIT_SNACKBAR = "LAUNCH_EDIT_SNACKBAR";
export const LAUNCH_ADD_SNACKBAR = "LAUNCH_ADD_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const ADD_CIRCLE_USER = "ADD_CIRCLE_USER";
export const ADD_CIRCLE = "ADD_CIRCLE";
export const REMOVE_CIRCLE_USER = "REMOVE_CIRCLE_USER";
export const REMOVE_CIRCLE = "REMOVE_CIRCLE";

export const OPEN_CIRCLE_FORM = "OPEN_CIRCLE_FORM";


export const FILTER_ARTIFACTS = "FILTER_ARTIFACTS";
export const OPEN_ARTIFACT_FORM = "EDIT_ARTIFACT_FORM";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";

export const INITIALIZE_ARTIFACTS = "INITIALIZE_ARTIFACTS";

export const GET_SOCKET = "GET_SOCKET";