export const EDIT_ARTIFACT_REQUEST = 'EDIT_ARTIFACT_REQUEST';
export const EDIT_ARTIFACT_SUCCESS = 'EDIT_ARTIFACT_SUCCESS';
export const EDIT_ARTIFACT_FAILURE = 'EDIT_ARTIFACT_FAILURE';

export const CREATE_ARTIFACT_REQUEST = 'CREATE_ARTIFACT_REQUEST';
export const CREATE_ARTIFACT_SUCCESS = 'CREATE_ARTIFACT_SUCCESS';
export const CREATE_ARTIFACT_FAILURE = 'CREATE_ARTIFACT_FAILURE';

export const GET_ARTIFACTS_REQUEST = 'GET_ARTIFACTS_REQUEST';
export const GET_ARTIFACTS_SUCCESS = 'GET_ARTIFACTS_SUCCESS';
export const GET_ARTIFACTS_FAILURE = 'GET_ARTIFACTS_FAILURE';

export const DELETE_ARTIFACT_REQUEST = 'DELETE_ARTIFACT_REQUEST';
export const DELETE_ARTIFACT_SUCCESS = 'DELETE_ARTIFACT_SUCCESS';
export const DELETE_ARTIFACT_FAILURE = 'DELETE_ARTIFACT_FAILURE';

export const CLEAR_ARTIFACTS = 'CLEAR_ARTIFACTS';