export const GET_ALL_CIRCLES_REQUEST = 'GET_ALL_CIRCLES_REQUEST';
export const GET_ALL_CIRCLES_SUCCESS = 'GET_ALL_CIRCLES_SUCCESS';
export const GET_ALL_CIRCLES_FAILURE = 'GET_ALL_CIRCLES_FAILURE';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const ADD_CIRCLE_REQUEST = 'ADD_CIRCLE_REQUEST';
export const ADD_CIRCLE_SUCCESS = 'ADD_CIRCLE_SUCCESS';
export const ADD_CIRCLE_FAILURE = 'ADD_CIRCLE_FAILURE';

export const ADD_CIRCLE_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_CIRCLE_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_CIRCLE_USER_FAILURE = 'ADD_USER_FAILURE';

export const ADD_CIRCLE_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_CIRCLE_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_CIRCLE_ADMIN_FAILURE = 'ADD_ADMIN_FAILURE';

export const DELETE_CIRCLE_REQUEST = 'DELETE_CIRCLE_REQUEST';
export const DELETE_CIRCLE_SUCCESS = 'DELETE_CIRCLE_SUCCESS';
export const DELETE_CIRCLE_FAILURE = 'DELETE_CIRCLE_FAILURE';

export const DELETE_CIRCLE_USER_REQUEST = 'DELETE_CIRCLE_USER_REQUEST';
export const DELETE_CIRCLE_USER_SUCCESS = 'DELETE_CIRCLE_USER_SUCCESS';
export const DELETE_CIRCLE_USER_FAILURE = 'DELETE_CIRCLE_USER_FAILURE';

export const DELETE_CIRCLE_ADMIN_REQUEST = 'DELETE_CIRCLE_ADMIN_REQUEST';
export const DELETE_CIRCLE_ADMIN_SUCCESS = 'DELETE_CIRCLE_ADMIN_SUCCESS';
export const DELETE_CIRCLE_ADMIN_FAILURE = 'DELETE_CIRCLE_ADMIN_FAILURE';

export const ADD_CIRCLE_ARTIFACT_REQUEST = 'ADD_CIRCLE_ARTIFACT_REQUEST';
export const ADD_CIRCLE_ARTIFACT_SUCCESS = 'ADD_CIRCLE_ARTIFACT_SUCCESS';
export const ADD_CIRCLE_ARTIFACT_FAILURE = 'ADD_CIRCLE_ARTIFACT_FAILURE';

export const ATTATCH_ARTIFACT = 'ATTATCH_ARTIFACT';
